name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      run: |
    - name: run tests 
      run: |
        python3 manage.py tests

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: deploy to production
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.  SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}


          script: |
            cd /home/azureuser/django-demon-app

            git pull origin main 

            pip install -r requirements.txt

            sudo systemctl restart gunicorn

            echo "Done"
